spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  jwt:
    secret : ${jwt_secret}

decorator:
  datasource:
    p6spy:
      enable-logging: false

logging:
  level:
    org.hibernate.SQL: error
